modLoader="javafml"
loaderVersion="[36,)"
license="ARR"

[[mods]]
modId="modname"
version="${file.jarVersion}"
displayName="ModName"
authors="Snownee"
displayURL="https://minecraft.curseforge.com/projects/modname"
description=""

[[dependencies.modname]]
    modId="kiwi"
    mandatory=true
    versionRange="[3.5, 3.11)"
    ordering="BEFORE"
    side="BOTH"
